### PR TITLE
API upgrades

### PR DESCRIPTION
**Pull request by psugihara**
- [x] limit dailies to n=21 past days
- [x] activity feed for 20 last runs today
- [x] bump to top 10 cumulative times for dailies
- [x] days in wallet json

Screenshot 2024-07-24 at 10 04 16 PM

https://github.com/trifle-labs/anybody-problem/issues/205

### CODE REVIEW

**Comment by okwme** [comment]
Looks good except I think the logic around streaks is wrong. It says that the current streak of 0xfa398d672936dcf428116f687244034961545d91 is 7 days but should only be 1 since i didn't play yesterday but did play today with that address:
```json
Anybody API /sse/base_sepolia/0xfa398d672936dcf428116f687244034961545d91
{
  "leaderboard": {
    "daily": {
      "1720137600": {
        "cumulative": []
      },
      "1720224000": {
        "cumulative": []
      },
      "1720310400": {
        "cumulative": [
          {
            "runId": 2,
            "day": 1720310400,
            "date": "2024-07-07",
            "time": 1371,
            "player": "0xfa398d672936dcf428116f687244034961545d91"
          }
        ]
      },
      "1720396800": {
        "cumulative": []
      },
      "1720483200": {
        "cumulative": [
          {
            "runId": 4,
            "day": 1720483200,
            "date": "2024-07-09",
            "time": 969,
            "player": "0xfa398d672936dcf428116f687244034961545d91"
          }
        ]
      },
      "1720569600": {
        "cumulative": [
          {
            "runId": 5,
            "day": 1720569600,
            "date": "2024-07-10",
            "time": 1492,
            "player": "0xfa398d672936dcf428116f687244034961545d91"
          }
        ]
      },
      "1720656000": {
        "cumulative": []
      },
      "1720742400": {
        "cumulative": []
      },
      "1720828800": {
        "cumulative": []
      },
      "1720915200": {
        "cumulative": [
          {
            "runId": 6,
            "day": 1720915200,
            "date": "2024-07-14",
            "time": 1112,
            "player": "0xfa398d672936dcf428116f687244034961545d91"
          }
        ]
      },
      "1721001600": {
        "cumulative": []
      },
      "1721088000": {
        "cumulative": [
          {
            "runId": 9,
            "day": 1721088000,
            "date": "2024-07-16",
            "time": 1583,
            "player": "0xc795344b1b30e3cfee1afa1d5204b141940cf445"
          }
        ]
      },
      "1721174400": {
        "cumulative": [
          {
            "runId": 10,
            "day": 1721174400,
            "date": "2024-07-17",
            "time": 1133,
            "player": "0xc795344b1b30e3cfee1afa1d5204b141940cf445"
          }
        ]
      },
      "1721260800": {
        "cumulative": [
          {
            "runId": 11,
            "day": 1721260800,
            "date": "2024-07-18",
            "time": 915,
            "player": "0xc795344b1b30e3cfee1afa1d5204b141940cf445"
          },
          {
            "runId": 12,
            "day": 1721260800,
            "date": "2024-07-18",
            "time": 1015,
            "player": "0xc795344b1b30e3cfee1afa1d5204b141940cf445"
          }
        ]
      },
      "1721347200": {
        "cumulative": [
          {
            "runId": 18,
            "day": 1721347200,
            "date": "2024-07-19",
            "time": 919,
            "player": "0xc795344b1b30e3cfee1afa1d5204b141940cf445"
          },
          {
            "runId": 17,
            "day": 1721347200,
            "date": "2024-07-19",
            "time": 1083,
            "player": "0xc795344b1b30e3cfee1afa1d5204b141940cf445"
          },
          {
            "runId": 19,
            "day": 1721347200,
            "date": "2024-07-19",
            "time": 1109,
            "player": "0x47e65bc714cd44959360ac0814a5fca0f5b07145"
          },
          {
            "runId": 16,
            "day": 1721347200,
            "date": "2024-07-19",
            "time": 1490,
            "player": "0xaf2ce0962d1a4b1aab10f7faa62bbbca40a8ea53"
          }
        ]
      },
      "1721433600": {
        "cumulative": [
          {
            "runId": 20,
            "day": 1721433600,
            "date": "2024-07-20",
            "time": 1550,
            "player": "0x47e65bc714cd44959360ac0814a5fca0f5b07145"
          }
        ]
      },
      "1721520000": {
        "cumulative": [
          {
            "runId": 22,
            "day": 1721520000,
            "date": "2024-07-21",
            "time": 1172,
            "player": "0x47e65bc714cd44959360ac0814a5fca0f5b07145"
          },
          {
            "runId": 21,
            "day": 1721520000,
            "date": "2024-07-21",
            "time": 1208,
            "player": "0x47e65bc714cd44959360ac0814a5fca0f5b07145"
          }
        ]
      },
      "1721606400": {
        "cumulative": [
          {
            "runId": 24,
            "day": 1721606400,
            "date": "2024-07-22",
            "time": 816,
            "player": "0xaf2ce0962d1a4b1aab10f7faa62bbbca40a8ea53"
          },
          {
            "runId": 23,
            "day": 1721606400,
            "date": "2024-07-22",
            "time": 1178,
            "player": "0xfa398d672936dcf428116f687244034961545d91"
          }
        ]
      },
      "1721692800": {
        "cumulative": [
          {
            "runId": 25,
            "day": 1721692800,
            "date": "2024-07-23",
            "time": 891,
            "player": "0xc795344b1b30e3cfee1afa1d5204b141940cf445"
          }
        ]
      },
      "1721779200": {
        "cumulative": [
          {
            "runId": 27,
            "day": 1721779200,
            "date": "2024-07-24",
            "time": 1449,
            "player": "0xc795344b1b30e3cfee1afa1d5204b141940cf445"
          }
        ]
      },
      "1721865600": {
        "cumulative": [
          {
            "runId": 28,
            "day": 1721865600,
            "date": "2024-07-25",
            "time": 1345,
            "player": "0xfa398d672936dcf428116f687244034961545d91"
          }
        ]
      }
    },
    "feed": [
      {
        "runId": 28,
        "day": 1721865600,
        "date": "2024-07-25",
        "time": 1345,
        "player": "0xfa398d672936dcf428116f687244034961545d91"
      }
    ],
    "allTime": {
      "mostSolved": [
        {
          "solved": 35,
          "player": "0xc795344b1b30e3cfee1afa1d5204b141940cf445"
        },
        {
          "solved": 35,
          "player": "0xfa398d672936dcf428116f687244034961545d91"
        },
        {
          "solved": 15,
          "player": "0x47e65bc714cd44959360ac0814a5fca0f5b07145"
        },
        {
          "solved": 15,
          "player": "0xaf2ce0962d1a4b1aab10f7faa62bbbca40a8ea53"
        },
        {
          "solved": 5,
          "player": "0xa8100e261bd3d7f20bb04686e9982574054d1d1c"
        }
      ],
      "currentStreak": [
        {
          "streak": 8,
          "player": "0xc795344b1b30e3cfee1afa1d5204b141940cf445"
        },
        {
          "streak": 7,
          "player": "0xfa398d672936dcf428116f687244034961545d91"
        }
      ],
      "longestStreak": [
        {
          "streak": 8,
          "player": "0xc795344b1b30e3cfee1afa1d5204b141940cf445"
        },
        {
          "streak": 7,
          "player": "0xfa398d672936dcf428116f687244034961545d91"
        },
        {
          "streak": 4,
          "player": "0x47e65bc714cd44959360ac0814a5fca0f5b07145"
        },
        {
          "streak": 2,
          "player": "0xaf2ce0962d1a4b1aab10f7faa62bbbca40a8ea53"
        }
      ],
      "fastest": [
        {
          "day": "1721606400",
          "date": "2024-07-22",
          "time": 816,
          "player": "0xaf2ce0962d1a4b1aab10f7faa62bbbca40a8ea53"
        },
        {
          "day": "1719532800",
          "date": "2024-06-28",
          "time": 823,
          "player": "0xfa398d672936dcf428116f687244034961545d91"
        },
        {
          "day": "1721692800",
          "date": "2024-07-23",
          "time": 891,
          "player": "0xc795344b1b30e3cfee1afa1d5204b141940cf445"
        },
        {
          "day": "1721260800",
          "date": "2024-07-18",
          "time": 915,
          "player": "0xc795344b1b30e3cfee1afa1d5204b141940cf445"
        },
        {
          "day": "1721347200",
          "date": "2024-07-19",
          "time": 919,
          "player": "0xc795344b1b30e3cfee1afa1d5204b141940cf445"
        },
        {
          "day": "1720483200",
          "date": "2024-07-09",
          "time": 969,
          "player": "0xfa398d672936dcf428116f687244034961545d91"
        },
        {
          "day": "1721260800",
          "date": "2024-07-18",
          "time": 1015,
          "player": "0xc795344b1b30e3cfee1afa1d5204b141940cf445"
        },
        {
          "day": "1721347200",
          "date": "2024-07-19",
          "time": 1083,
          "player": "0xc795344b1b30e3cfee1afa1d5204b141940cf445"
        },
        {
          "day": "1721347200",
          "date": "2024-07-19",
          "time": 1109,
          "player": "0x47e65bc714cd44959360ac0814a5fca0f5b07145"
        },
        {
          "day": "1720915200",
          "date": "2024-07-14",
          "time": 1112,
          "player": "0xfa398d672936dcf428116f687244034961545d91"
        }
      ],
      "daysPlayed": [
        {
          "player": "0xfa398d672936dcf428116f687244034961545d91",
          "daysPlayed": 7
        },
        {
          "player": "0xc795344b1b30e3cfee1afa1d5204b141940cf445",
          "daysPlayed": 5
        },
        {
          "player": "0x47e65bc714cd44959360ac0814a5fca0f5b07145",
          "daysPlayed": 3
        },
        {
          "player": "0xaf2ce0962d1a4b1aab10f7faa62bbbca40a8ea53",
          "daysPlayed": 2
        },
        {
          "player": "0xa8100e261bd3d7f20bb04686e9982574054d1d1c",
          "daysPlayed": 1
        }
      ]
    }
  },
  "wallet": {
    "currentStreak": 7,
    "longestStreak": 7,
    "fastestCompleted": {
      "runId": "1",
      "day": "1719532800",
      "time": 823
    },
    "daysPlayed": [
      1720310400,
      1720396800,
      1720483200,
      1720569600,
      1721001600,
      1721606400,
      1721865600
    ],
    "levelsSolved": 35
  },
  "address": "0xfa398d672936dcf428116f687244034961545d91"
}
```

**Comment by psugihara** [comment]
cool, thanks for testing. Will debug w this user

**Comment by psugihara** [comment]
Screenshot 2024-07-25 at 10 24 02 AM

@okwme are you saying total solved and days solved should both be about runs? i guess I don't understand the difference. Like if saved it multiple times in a day?

**Comment by psugihara** [comment]
- [ ] feed items should include rank

Screenshot 2024-07-25 at 10 31 07 AM

**Comment by psugihara** [comment]
> Also all time most solved is number of solved levels instead of number of solved runs. 

we no longer display this so i'll remove it?

**Comment by psugihara** [comment]
OK, I think streak stuff is sorted and I think we have everything. Was able to rewrite in a simpler way with less nesting, then validated for that user.

For 0xfa398d672936dcf428116f687244034961545d91, we have these days

1719532800 = 2024-06-27
1720310400 = 2024-07-06
1720396800 = 2024-07-07
1720483200 = 2024-07-08
1720569600 = 2024-07-09
1720915200 = 2024-07-13
1721001600 = 2024-07-14
1721606400 = 2024-07-21
1721865600 = 2024-07-24

Longest streak: 4
Current streak: 1

```
{
  "leaderboard": {
    "daily": {
      "1720137600": {
        "cumulative": []
      },
      "1720224000": {
        "cumulative": []
      },
      "1720310400": {
        "cumulative": [
          {
            "runId": 2,
            "day": 1720310400,
            "date": "2024-07-07",
            "time": 1371,
            "player": "0xfa398d672936dcf428116f687244034961545d91"
          }
        ]
      },
      "1720396800": {
        "cumulative": [
          {
            "runId": 3,
            "day": 1720396800,
            "date": "2024-07-08",
            "time": 808,
            "player": "0xfa398d672936dcf428116f687244034961545d91"
          }
        ]
      },
      "1720483200": {
        "cumulative": [
          {
            "runId": 4,
            "day": 1720483200,
            "date": "2024-07-09",
            "time": 969,
            "player": "0xfa398d672936dcf428116f687244034961545d91"
          }
        ]
      },
      "1720569600": {
        "cumulative": [
          {
            "runId": 5,
            "day": 1720569600,
            "date": "2024-07-10",
            "time": 1492,
            "player": "0xfa398d672936dcf428116f687244034961545d91"
          }
        ]
      },
      "1720656000": {
        "cumulative": []
      },
      "1720742400": {
        "cumulative": []
      },
      "1720828800": {
        "cumulative": []
      },
      "1720915200": {
        "cumulative": [
          {
            "runId": 6,
            "day": 1720915200,
            "date": "2024-07-14",
            "time": 1112,
            "player": "0xfa398d672936dcf428116f687244034961545d91"
          }
        ]
      },
      "1721001600": {
        "cumulative": [
          {
            "runId": 7,
            "day": 1721001600,
            "date": "2024-07-15",
            "time": 857,
            "player": "0xfa398d672936dcf428116f687244034961545d91"
          },
          {
            "runId": 8,
            "day": 1721001600,
            "date": "2024-07-15",
            "time": 1831,
            "player": "0xaf2ce0962d1a4b1aab10f7faa62bbbca40a8ea53"
          }
        ]
      },
      "1721088000": {
        "cumulative": [
          {
            "runId": 9,
            "day": 1721088000,
            "date": "2024-07-16",
            "time": 1583,
            "player": "0xc795344b1b30e3cfee1afa1d5204b141940cf445"
          }
        ]
      },
      "1721174400": {
        "cumulative": [
          {
            "runId": 10,
            "day": 1721174400,
            "date": "2024-07-17",
            "time": 1133,
            "player": "0xc795344b1b30e3cfee1afa1d5204b141940cf445"
          }
        ]
      },
      "1721260800": {
        "cumulative": [
          {
            "runId": 11,
            "day": 1721260800,
            "date": "2024-07-18",
            "time": 915,
            "player": "0xc795344b1b30e3cfee1afa1d5204b141940cf445"
          },
          {
            "runId": 12,
            "day": 1721260800,
            "date": "2024-07-18",
            "time": 1015,
            "player": "0xc795344b1b30e3cfee1afa1d5204b141940cf445"
          },
          {
            "runId": 13,
            "day": 1721260800,
            "date": "2024-07-18",
            "time": 1415,
            "player": "0xa8100e261bd3d7f20bb04686e9982574054d1d1c"
          },
          {
            "runId": 14,
            "day": 1721260800,
            "date": "2024-07-18",
            "time": 1816,
            "player": "0xaf2ce0962d1a4b1aab10f7faa62bbbca40a8ea53"
          },
          {
            "runId": 15,
            "day": 1721260800,
            "date": "2024-07-18",
            "time": 1816,
            "player": "0xaf2ce0962d1a4b1aab10f7faa62bbbca40a8ea53"
          }
        ]
      },
      "1721347200": {
        "cumulative": [
          {
            "runId": 18,
            "day": 1721347200,
            "date": "2024-07-19",
            "time": 919,
            "player": "0xc795344b1b30e3cfee1afa1d5204b141940cf445"
          },
          {
            "runId": 17,
            "day": 1721347200,
            "date": "2024-07-19",
            "time": 1083,
            "player": "0xc795344b1b30e3cfee1afa1d5204b141940cf445"
          },
          {
            "runId": 19,
            "day": 1721347200,
            "date": "2024-07-19",
            "time": 1109,
            "player": "0x47e65bc714cd44959360ac0814a5fca0f5b07145"
          },
          {
            "runId": 16,
            "day": 1721347200,
            "date": "2024-07-19",
            "time": 1490,
            "player": "0xaf2ce0962d1a4b1aab10f7faa62bbbca40a8ea53"
          }
        ]
      },
      "1721433600": {
        "cumulative": [
          {
            "runId": 20,
            "day": 1721433600,
            "date": "2024-07-20",
            "time": 1550,
            "player": "0x47e65bc714cd44959360ac0814a5fca0f5b07145"
          }
        ]
      },
      "1721520000": {
        "cumulative": [
          {
            "runId": 22,
            "day": 1721520000,
            "date": "2024-07-21",
            "time": 1172,
            "player": "0x47e65bc714cd44959360ac0814a5fca0f5b07145"
          },
          {
            "runId": 21,
            "day": 1721520000,
            "date": "2024-07-21",
            "time": 1208,
            "player": "0x47e65bc714cd44959360ac0814a5fca0f5b07145"
          }
        ]
      },
      "1721606400": {
        "cumulative": [
          {
            "runId": 24,
            "day": 1721606400,
            "date": "2024-07-22",
            "time": 816,
            "player": "0xaf2ce0962d1a4b1aab10f7faa62bbbca40a8ea53"
          },
          {
            "runId": 23,
            "day": 1721606400,
            "date": "2024-07-22",
            "time": 1178,
            "player": "0xfa398d672936dcf428116f687244034961545d91"
          }
        ]
      },
      "1721692800": {
        "cumulative": [
          {
            "runId": 26,
            "day": 1721692800,
            "date": "2024-07-23",
            "time": 733,
            "player": "0xc795344b1b30e3cfee1afa1d5204b141940cf445"
          },
          {
            "runId": 25,
            "day": 1721692800,
            "date": "2024-07-23",
            "time": 891,
            "player": "0xc795344b1b30e3cfee1afa1d5204b141940cf445"
          }
        ]
      },
      "1721779200": {
        "cumulative": [
          {
            "runId": 27,
            "day": 1721779200,
            "date": "2024-07-24",
            "time": 1449,
            "player": "0xc795344b1b30e3cfee1afa1d5204b141940cf445"
          }
        ]
      },
      "1721865600": {
        "cumulative": [
          {
            "runId": 28,
            "day": 1721865600,
            "date": "2024-07-25",
            "time": 1345,
            "player": "0xfa398d672936dcf428116f687244034961545d91"
          }
        ]
      }
    },
    "feed": [
      {
        "rank": 1,
        "runId": 28,
        "day": 1721865600,
        "date": "2024-07-25",
        "time": 1345,
        "player": "0xfa398d672936dcf428116f687244034961545d91"
      }
    ]
  },
  "wallet": {
    "currentStreak": 1,
    "longestStreak": 4,
    "fastestCompleted": {
      "runId": "3",
      "day": "1720396800",
      "time": 808
    },
    "daysPlayed": [
      1719532800,
      1720310400,
      1720396800,
      1720483200,
      1720569600,
      1720915200,
      1721001600,
      1721606400,
      1721865600
    ],
    "runsSolved": 9
  },
  "address": "0xfa398d672936dcf428116f687244034961545d91"
}
```

**Comment by psugihara** [comment]
I added a little endpoint so that you can check what rank a user will have before they save.

/rank?time=1345
Screenshot 2024-07-25 at 3 26 25 PM
Screenshot 2024-07-25 at 3 26 18 PM
Screenshot 2024-07-25 at 3 26 12 PM

**Comment by okwme** [comment]
🏆

**Pull request merged**
