### PR TITLE
Audio refactor

### PR DESCRIPTION
**Pull request by okwme**

### CODE REVIEW

**Comment by okwme** [comment]
confirmed the game freeze bug does not happen in this PR because the game over audio speed up thing is removed here too

https://github.com/trifle-labs/anybody-problem/issues/253

**Comment by okwme** [comment]
nice!

first impressions are good. Couple things stand out:
 - missile shots sound too quiet now (i think i fixed)
 - song restarts when the end of level screen (i think i fixed)
 - seeing `Start time must be strictly greater than previous start time` errors again (used to see them a lot)
 - mute as a setting doesn't seem to work, I added a key listener to M but see no reaction when `this.mute = true`
 - i tried tweaking the change rate thing but when i add it back it still makes the app crash, need to look further into it

**Comment by dataexcess** [comment]
@okwme My bad, I forgot to add the muted code. Fixed.

**Comment by dataexcess** [comment]
@okwme started a new PR to address these remaining issues.

Added mute functionality.
Added the gameover sounds again. Cannot reproduce crash but maybe my. laptop is too slow hah. Curious if this refactor might have fixed it?
Cannot see the 'Start time must be strictly greater' error anymore.

https://github.com/trifle-labs/anybody-problem/pull/292

**Pull request merged**
