### PR TITLE
add most days played to leaderboard result

### PR DESCRIPTION
**Pull request by psugihara**
This adds `leaderboard.allTime.daysPlayed` as discussed in https://github.com/trifle-labs/anybody-problem-frontend/pull/66

I also tweaked most solved to be most solutions. I think this could be a cool and high scoring variation or we can remove if its spammy.

### CODE REVIEW

**Comment by psugihara** [comment]
snapshot of the output w my local data:

```
{
  leaderboard: {
    daily: {
      '1717632000': { levels: [], cumulative: [] },
      '1717718400': {
        levels: [
          {
            level: 2,
            events: [
              {
                problemId: '3',
                ticks: 44,
                owner: '0x2363643a1bf43fe9d8fbc0630c706003b4e062bf'
              },
              {
                problemId: '1',
                ticks: 45,
                owner: '0xfa398d672936dcf428116f687244034961545d91'
              },
              {
                problemId: '2',
                ticks: 46,
                owner: '0xfa398d672936dcf428116f687244034961545d91'
              }
            ]
          },
          {
            level: 3,
            events: [
              {
                problemId: '3',
                ticks: 108,
                owner: '0x2363643a1bf43fe9d8fbc0630c706003b4e062bf'
              },
              {
                problemId: '1',
                ticks: 188,
                owner: '0xfa398d672936dcf428116f687244034961545d91'
              },
              {
                problemId: '2',
                ticks: 512,
                owner: '0xfa398d672936dcf428116f687244034961545d91'
              }
            ]
          },
          {
            level: 4,
            events: [
              {
                problemId: '2',
                ticks: 626,
                owner: '0xfa398d672936dcf428116f687244034961545d91'
              },
              {
                problemId: '1',
                ticks: 1373,
                owner: '0xfa398d672936dcf428116f687244034961545d91'
              }
            ]
          },
          {
            level: 5,
            events: [
              {
                problemId: '2',
                ticks: 610,
                owner: '0xfa398d672936dcf428116f687244034961545d91'
              },
              {
                problemId: '1',
                ticks: 870,
                owner: '0xfa398d672936dcf428116f687244034961545d91'
              }
            ]
          },
          {
            level: 6,
            events: [
              {
                problemId: '2',
                ticks: 301,
                owner: '0xfa398d672936dcf428116f687244034961545d91'
              }
            ]
          },
          {
            level: 7,
            events: [
              {
                problemId: '2',
                ticks: 361,
                owner: '0xfa398d672936dcf428116f687244034961545d91'
              }
            ]
          },
          {
            level: 8,
            events: [
              {
                problemId: '2',
                ticks: 220,
                owner: '0xfa398d672936dcf428116f687244034961545d91'
              }
            ]
          }
        ],
        cumulative: [
          {
            problemId: '2',
            ticks: 2676,
            owner: '0xfa398d672936dcf428116f687244034961545d91'
          }
        ]
      },
      '1717804800': { levels: [], cumulative: [] },
      '1717891200': { levels: [], cumulative: [] },
      '1717977600': { levels: [], cumulative: [] }
    },
    allTime: {
      mostSolved: [
        { solved: 11, owner: '0xfa398d672936dcf428116f687244034961545d91' },
        { solved: 2, owner: '0x2363643a1bf43fe9d8fbc0630c706003b4e062bf' }
      ],
      currentStreak: [],
      fastest: [],
      daysPlayed: [
        { owner: '0xfa398d672936dcf428116f687244034961545d91', daysPlayed: 1 }
      ]
    },
    problems: {
      '1': {
        owner: '0xfa398d672936dcf428116f687244034961545d91',
        bodies: [
          {
            problemId: '1',
            bodyId: '1',
            tick: 0,
            px: 629826,
            py: 203907,
            radius: 36000,
            seed: '0xc888db550c36b5b344e4e803973808c947a6e31d1f9e25edec88e91803903bed',
            owner: '0xfa398d672936dcf428116f687244034961545d91',
            mintedBodyIndex: 0
          },
          {
            problemId: '1',
            bodyId: '2',
            tick: 0,
            px: 734968,
            py: 425167,
            radius: 7000,
            seed: '0x9a49df4ec6619041ad853f40311bc5b964e253d640ba32f96467c62458c35e8d',
            owner: '0xfa398d672936dcf428116f687244034961545d91',
            mintedBodyIndex: 1
          },
          {
            problemId: '1',
            bodyId: '3',
            tick: 45,
            px: 396504,
            py: 308445,
            radius: 7000,
            seed: '0xa3d46143eed0709e11130471f8482f882e664ec1eea3cc5403c07c24a7980957',
            owner: '0xfa398d672936dcf428116f687244034961545d91',
            mintedBodyIndex: 2
          },
          {
            problemId: '1',
            bodyId: '4',
            tick: 233,
            px: 458620,
            py: 837912,
            radius: 7000,
            seed: '0x5ccac475eed362b20cd3c83af284b4a0e3188f0a4361aaa40f31cade97de709c',
            owner: '0xfa398d672936dcf428116f687244034961545d91',
            mintedBodyIndex: 3
          },
          {
            problemId: '1',
            bodyId: '5',
            tick: 1606,
            px: 338738,
            py: 335587,
            radius: 7000,
            seed: '0xe6599ddab129178d900480d45ef24b7225bfdabf4fb4a6dea5702705de8f0e6d',
            owner: '0xfa398d672936dcf428116f687244034961545d91',
            mintedBodyIndex: 4
          },
          {
            problemId: '1',
            bodyId: '6',
            tick: 2476,
            px: 924971,
            py: 267239,
            radius: 12000,
            seed: '0xe3a0aeb237ceb84067d18f62de808c5d2babc1729fc53bbc387f37628a2c1851',
            owner: '0xfa398d672936dcf428116f687244034961545d91',
            mintedBodyIndex: 5
          }
        ]
      },
      '2': {
        owner: '0xfa398d672936dcf428116f687244034961545d91',
        bodies: [
          {
            problemId: '2',
            bodyId: '7',
            tick: 0,
            px: 629826,
            py: 203907,
            radius: 36000,
            seed: '0xd98188b2227f73eea1d4e39fe0209e684ed33d7dfbc7602d66358766c799a94f',
            owner: '0xfa398d672936dcf428116f687244034961545d91',
            mintedBodyIndex: 0
          },
          {
            problemId: '2',
            bodyId: '8',
            tick: 0,
            px: 734968,
            py: 425167,
            radius: 7000,
            seed: '0xf7240cd70a1fff3073a110580e04a474e433e1eff50c981ed7cd92ddede93e85',
            owner: '0xfa398d672936dcf428116f687244034961545d91',
            mintedBodyIndex: 1
          },
          {
            problemId: '2',
            bodyId: '9',
            tick: 46,
            px: 396504,
            py: 308445,
            radius: 7000,
            seed: '0x61adfbf6bfdfb407d5e6467873692e02bbfddd15cc5ecfa12f76e3cfe0f751d6',
            owner: '0xfa398d672936dcf428116f687244034961545d91',
            mintedBodyIndex: 2
          },
          {
            problemId: '2',
            bodyId: '10',
            tick: 558,
            px: 458620,
            py: 837912,
            radius: 7000,
            seed: '0x4ab52d8ebee67a983dd978f6c9c9521f6501bc234505dc77615d27a5cdda4248',
            owner: '0xfa398d672936dcf428116f687244034961545d91',
            mintedBodyIndex: 3
          },
          {
            problemId: '2',
            bodyId: '11',
            tick: 1184,
            px: 338738,
            py: 335587,
            radius: 7000,
            seed: '0xf9df95a7edc8f2b68ae130894a91d0ea9add3cb74d13da204e93bf1aa1588688',
            owner: '0xfa398d672936dcf428116f687244034961545d91',
            mintedBodyIndex: 4
          },
          {
            problemId: '2',
            bodyId: '12',
            tick: 1794,
            px: 924971,
            py: 267239,
            radius: 12000,
            seed: '0x5890d349cc68105e9e87c4e718e85cc16dfb355f89eeec5030fa00425367ddb3',
            owner: '0xfa398d672936dcf428116f687244034961545d91',
            mintedBodyIndex: 5
          },
          {
            problemId: '2',
            bodyId: '13',
            tick: 2095,
            px: 721488,
            py: 45296,
            radius: 7000,
            seed: '0x7610f585409bf680b94a1afe1a2f1b498c4af0741ba915c90d5ed2cdb0f042cb',
            owner: '0xfa398d672936dcf428116f687244034961545d91',
            mintedBodyIndex: 6
          },
          {
            problemId: '2',
            bodyId: '14',
            tick: 2456,
            px: 534609,
            py: 752941,
            radius: 12000,
            seed: '0x0d6a49e4424e8f9b208659a0ec833d3c47fe09954da432c86a83adbc2900c33a',
            owner: '0xfa398d672936dcf428116f687244034961545d91',
            mintedBodyIndex: 7
          }
        ]
      },
      '3': {
        owner: '0x2363643a1bf43fe9d8fbc0630c706003b4e062bf',
        bodies: [
          {
            problemId: '3',
            bodyId: '15',
            tick: 0,
            px: 629826,
            py: 203907,
            radius: 36000,
            seed: '0x566e6d24b501ff86cb13df2ef10f07c7c33f9012f754e6c44a656cc1e72ea3ff',
            owner: '0x2363643a1bf43fe9d8fbc0630c706003b4e062bf',
            mintedBodyIndex: 0
          },
          {
            problemId: '3',
            bodyId: '16',
            tick: 0,
            px: 734968,
            py: 425167,
            radius: 7000,
            seed: '0x82697f92c48f9923b0bc0decd04e210a34874f8148f9c3d52bbe9d1907acc6f8',
            owner: '0x2363643a1bf43fe9d8fbc0630c706003b4e062bf',
            mintedBodyIndex: 1
          },
          {
            problemId: '3',
            bodyId: '17',
            tick: 44,
            px: 396504,
            py: 308445,
            radius: 7000,
            seed: '0xb0acdc16ab29a10e4a15bac548651f089b3f3ecec606cecf2196b5a334518164',
            owner: '0x2363643a1bf43fe9d8fbc0630c706003b4e062bf',
            mintedBodyIndex: 2
          },
          {
            problemId: '3',
            bodyId: '18',
            tick: 152,
            px: 458620,
            py: 837912,
            radius: 7000,
            seed: '0x2655f9623cb54e256fccb1fec550092bf13189cba7b7a1f4421d542c63ea1797',
            owner: '0x2363643a1bf43fe9d8fbc0630c706003b4e062bf',
            mintedBodyIndex: 3
          }
        ]
      }
    }
  }
}
```

**Review by okwme — APPROVED** [review]
LGTM, let's keep all time levels for now can decide whether we show it or not down the road as long as it's not a huge performance impact (which i assume not)

**Comment by okwme** [comment]
question: what's the integration process like here? open PR isn't possible to test against a front end very easily is it? Only when it gets merged into main does the server rebuild and refresh with new schema?

**Comment by psugihara** [comment]
we don't have a staging env so unless the branch is switched in digital ocean, you just have to test locally by booting it as described in the readme https://github.com/trifle-labs/anybody-problem/tree/main/server

current digital ocean branch is main, but easy to switch around here
Screenshot 2024-06-11 at 9 09 14 AM

Screenshot 2024-06-11 at 9 09 24 AM

**Pull request merged**
